version: '3'
services:
  catalogue_distribution:
    container_name: cassandraNode
    image: cassandra:latest
    restart: always
    ports:
    - 7000:7000
    - 7001:7001
    - 7199:7199
    - 9042:9042
    - 9160:9160
    - 9404:9404
    volumes:
    - cassandra:/var/lib/cassandra
    environment:
    - CASSANDRA_SEEDS=10.10.10.2, 10.10.10.3
    - CASSANDRA_BROADCAST_ADDRESS=10.10.10.3
volumes:
  cassandra:
    external: true
